"""
_build_documentation.py - merge docs/ARCHITECTURE.md and docs/UML_DIAGRAMS.md
into a single project-root DOCUMENTATION.md.

Rationale: two files in docs/ were easy to miss; one file at the repo root
is the entry point a reviewer opens first.

The merge is mechanical and repeatable:
  * strip each source's H1 title block (kept once, at the top of the output)
  * renumber the UML section headings from "## N." to "## 6.N" so all
    diagram sections sit inside the architecture numbering
  * generate a fresh table of contents from the final headings
  * preserve every code fence and table verbatim

Run:  python docs/uml/_build_documentation.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
DOCS = ROOT / "docs"
ARCH = DOCS / "ARCHITECTURE.md"
UML = DOCS / "UML_DIAGRAMS.md"
OUT = ROOT / "DOCUMENTATION.md"

HEADER = """# 🏺 Indus–Keeladi CNN — Project Documentation

> Consolidated developer reference for the Indus Valley Script ↔ Keeladi graffiti
> deep learning pipeline (TensorFlow 2.21 / Keras 3, Python 3.11).

| Document | Purpose |
|---|---|
| **`DOCUMENTATION.md`** *(this file)* | Architecture reference + all 14 UML diagrams |
| [`docs/ANALYSIS_ACCURACY_ROADMAP.md`](docs/ANALYSIS_ACCURACY_ROADMAP.md) | Research analysis, failure taxonomy, accuracy roadmap |
| [`README.md`](README.md) | Quick-start and how-to-run guide |
| [`docs/uml/`](docs/uml/) | Standalone `.puml` sources, one file per diagram |

---
"""

TOC_NOTE = (
    "<!-- TOC is regenerated by docs/uml/_build_documentation.py -->\n"
    "## Table of Contents\n"
)


def strip_title_block(text):
    """Drop the leading H1 and its intro blockquote, keep from the first '---'."""
    lines = text.splitlines()
    # find the first horizontal rule that follows the H1
    for i, l in enumerate(lines):
        if i > 0 and l.strip() == "---":
            return "\n".join(lines[i:]).lstrip("\n")
    return text


def renumber_uml_sections(text):
    """Move the UML block under its own top-level section.

    The architecture body already uses '## 6. Execution Flows', so the diagram
    sections are renumbered to '## 13. UML Diagrams' / '### 13.N ...' to avoid
    colliding with it. The old 'How to render' / 'Index' / conventions blocks
    become subsections too, so the whole file has one flat, consistent heading
    hierarchy.
    """
    lines = text.splitlines()
    out = []
    emit_top = False
    for l in lines:
        m = re.match(r"^## (\d+)\.\s+(.*)$", l)
        if m:
            if not emit_top:
                out.append("## 13. UML Diagrams")
                out.append("")
                out.append("> 14 PlantUML diagrams covering the system context, components, "
                           "classes, sequences, activities, state, deployment, packages "
                           "and use cases.")
                out.append("")
                emit_top = True
            out.append(f"### 13.{m.group(1)} {m.group(2)}")
        elif l.startswith("## How to render"):
            out.append("### 13.0 How to render")
        elif l.startswith("## Index"):
            out.append("### 13.0.1 Index")
        elif l.startswith("## Diagram Conventions"):
            out.append("### 13.15 Diagram conventions")
        elif l.startswith("## Validating the sources"):
            out.append("### 13.16 Validating the sources")
        else:
            out.append(l)
    return "\n".join(out)


def demote_headings(text, levels=1):
    """Push any remaining '#'-level heading down so it nests under '## 13.'."""
    res = []
    for l in text.splitlines():
        if re.match(r"^###\s", l):
            res.append("#" * (3 + levels) + l[3:])
        elif re.match(r"^####\s", l):
            res.append("#" * (4 + levels) + l[4:])
        else:
            res.append(l)
    return "\n".join(res)


def build_toc(text):
    """Build a nested TOC from '#', '##' and '###' headings (skipping the H1)."""
    lines = []
    for l in text.splitlines():
        m = re.match(r"^(#{2,3})\s+(.*)$", l)
        if not m:
            continue
        depth = len(m.group(1))
        title = m.group(2).strip()
        anchor = re.sub(r"[^a-z0-9\- ]", "", title.lower()).replace(" ", "-")
        lines.append(f"{'  ' * (depth - 2)}- [{title}](#{anchor})")
    return "\n".join(lines)


def main():
    if not ARCH.exists() or not UML.exists():
        print("ERROR: source documents missing", file=sys.stderr)
        return 1

    arch_body = strip_title_block(ARCH.read_text(encoding="utf-8"))
    uml_body = renumber_uml_sections(strip_title_block(UML.read_text(encoding="utf-8")))

    # UML's own "How to render" / "Index" / conventions stay as subsections 6.0.x
    body = arch_body.rstrip() + "\n\n" + uml_body.rstrip() + "\n"

    doc = HEADER + "\n" + TOC_NOTE + "\n" + build_toc(body) + "\n\n---\n\n" + body

    OUT.write_text(doc, encoding="utf-8")
    print(f"wrote {OUT}")
    print(f"  lines: {len(doc.splitlines())}")
    print(f"  bytes: {len(doc.encode('utf-8'))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())